-- トレーニングテーブルのRLSを無効化（開発用）
-- 作成日: 2025-10-07

ALTER TABLE trainings DISABLE ROW LEVEL SECURITY;
ALTER TABLE training_menus DISABLE ROW LEVEL SECURITY;
ALTER TABLE menu_trainings DISABLE ROW LEVEL SECURITY;
ALTER TABLE training_records DISABLE ROW LEVEL SECURITY;
ALTER TABLE templates DISABLE ROW LEVEL SECURITY;
ALTER TABLE template_trainings DISABLE ROW LEVEL SECURITY;
